name: Test and Deploy to Heroku

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

# TODO: extract node version to a variable
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install

      - name: Run Linters
        run: npm run lint

      - name: Run Formater
        run: npm run format

# TODO: extract image name to a variable
      - name: Build Docker Image
        run: docker build -t personal-website:1.0 .

  deploy:
    name: Deploy to Heroku
    needs: build-and-test
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

# TODO: extract node version to a variable
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install
    
      - name: Build Docker Image
        run: docker-compose up --build -d
    
      - name: Login to the Heroku Container Registry
        run: heroku container:login
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        
      - name: Tag and Push Docker Image to Heroku
        run:
          docker tag personal-website:1.0 registry.heroku.com/ben-teoh-website/web
          docker push registry.heroku.com/ben-teoh-website/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Docker Image to Heroku
        run: heroku container:release web -a ben-teoh-website
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}